#!/bin/sh -e

case "$1" in
    # do not stop the firewall during an upgrade
    remove)
        if [ -x "/usr/sbin/invoke-rc.d" ]
        then
            invoke-rc.d shorewall stop        
        else
            /etc/init.d/shorewall stop
        fi
        ;;
    upgrade|deconfigure|failed-upgrade)
        ;;
    *)
        echo "prerem called with unknown argument \`$1\'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
