#
# Shorewall version 5 - Sieve Macro
#
# /usr/share/shorewall/macro.Sieve
#
#	This macro handles sieve aka ManageSieve protocol.
#
###############################################################################
?FORMAT 2
###############################################################################
#ACTION	SOURCE	DEST	PROTO	DEST	SOURCE	ORIGIN	RATE	USER/
#				PORT(S)	PORT(S)	DEST	LIMIT	GROUP
PARAM	-	-	tcp	4190
