#
# Shorewall version 4 - HTTP Macro
#
# /usr/share/shorewall/macro.HTTP
#
#	This macro handles plaintext HTTP (WWW) traffic.
#
###############################################################################
#ACTION	SOURCE	DEST	PROTO	DEST	SOURCE	ORIGINAL	RATE	USER/
#				PORT	PORT(S)	DEST		LIMIT	GROUP
PARAM	-	-	tcp	80
#LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE
