#!/bin/sh
#
#     Shorewall interface helper utility - V4.2
#
#     (c) 2007,2014 - Tom Eastep (teastep@shorewall.net)
#
#	This file is installed in /usr/share/shorewall/wait4ifup
#
#	Shorewall documentation is available at http://www.shorewall.net
#
#       This program is part of Shorewall.
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by the
#       Free Software Foundation, either version 2 of the license or, at your
#       option, any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, see <http://www.gnu.org/licenses/>.
#
#	If an error occurs while starting or restarting the firewall, the
#	firewall is automatically stopped.
#
#	The firewall uses configuration files in /etc/shorewall/ - skeleton
#	files is included with the firewall.
#
#	wait4ifup <interface> [ <seconds to wait> ]
#

interface_is_up() {
    [ -n "$(/sbin/ip link list dev $1 2> /dev/null | /bin/grep -e '[<,]UP[,>]')" ]
}

case $# in
    1)
	timeout=60
	;;
    2)
	timeout=$2
	;;
    *)
	echo "usage: $(basename $0) <interface> [ <timeout> ]"
	exit 2
	;;
esac

while [ $timeout -gt 0 ]; do
    interface_is_up $1 && exit 0
    /bin/sleep 1
    timeout=$(( $timeout - 1 ))
done

exit 1


