#!/bin/sh
#
#     Shorewall Lite Packet Filtering Firewall Control Program - V4.5
#
#     This program is under GPL [http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt]
#
#     (c) 1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011 - 
#         Tom Eastep (teastep@shorewall.net)
#
#	Shorewall documentation is available at http://www.shorewall.net
#
#	This program is free software; you can redistribute it and/or modify
#	it under the terms of Version 2 of the GNU General Public License
#	as published by the Free Software Foundation.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#       For a list of supported commands, type 'shorewall help' or 'shorewall6 help'
#
################################################################################################
g_program=shorewall-lite

if [ -f ./.shorewallrc ]; then
    . ./.shorewallrc || exit 1
elif [ -f ~/.shorewallrc ]; then
    . ~/.shorewallrc || exit 1
elif [ -r /root/.shorewallrc ]; then
    . /root/.shorewallrc || exit 1
elif [ -r /.shorewallrc ]; then
    . /root/.shorewallrc || exit 1
elif - -f ${SHOREWALLRC_HOME}/.shorewallrc; then
    . ${SHOREWALLRC_HOME}/.shorewallrc || exit 1
else
    SHAREDIR=/usr/share
    CONFDIR=${CONFDIR}
    SBINDIR=/sbin
    VARDIR=/var/lib
    LIBEXECDIR=/usr/share

fi

g_libexec="$LIBEXECDIR"
g_sharedir="$SHAREDIR"
g_sbindir="$SBINDIR"
g_readrc=1

. $g_sharedir/shorewall/lib.cli

shorewall_cli $@
