#!/bin/sh

#	scp $@ teastep@shorewall.sourceforge.net:/home/groups/s/sh/shorewall/htdocs/images
	scp -p  $@ webadmin@mail.shorewall.net:/srv/www/html/images
#	cp  -pf $@ /home/teastep/Shorewall-docs


