#!/bin/sh -e


case "$1" in
	configure)
	if which install-docs >/dev/null 2>&1; then
	    install-docs -i /usr/share/doc-base/shorewall-doc
	fi
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
	;;
esac

#DEBHELPER#
